### ISSUE TITLE
[META] Backdropcms.org and forum.backdropcms.org SEO Task Force

### ISSUE THREAD

**Issue by rayjamesdev** [backdrop-ops/backdrop-community#25]
This group meets during the second half of office hours each week.  The TODO list in this top message will be updated regularly to reflect current progress.

**TODOs:**
- [ ] Change/add Drupal lingo to Meta info in source header on front page of backdropcms.org.  @keiserjb
- [ ] setup a looker studio dashboard through GA4/search console, used to be data studio. Links GA4 and Search console. https://www.youtube.com/watch?v=igslsT0XLaU (Using Google Data (now Looker) Studio for Dashboard Analytics Reporting). @keiserjb will create one for each property.
- [ ] @stpaultim, ask perms to add/change header on main page to add Drupal 7 Fork lingo(Based on Irina suggestion)
- [ ] create more backlinks from Drupal
      - [ ] backlinks from Drupal 7 modules to the module port page on backdrop site.
      - [ ] backlinks from backdrop github project pages to project page on backdrop site.
      - [ ] @jenlampton  wants to know if we can automate this, figure out if we can. If not automate-able, at least create/update docs page that explains the process.      
- [ ] Need a roadmap for the task force (goals, todos, current site audits, hotjar, etc).
- [ ] Need an seo site audit for all sites, including lighthouse, search rankings, keywords, etc.
      - [ ] identify places where we need to show up that we are not showing up and solve it.
      - [ ] Search Console crawl reports.
- [x] Need a project setup at https://github.com/backdrop-ops/backdrop-community/projects @stpaultim .
- [x] Get and verify that Google (and other search engines) are crawling both sites.      
- [ ] Experiment with Hot Jar or other Heat Mapping Tool (https://github.com/backdrop-ops/backdrop-community/issues/27).
- [ ] Google free adwords credits?  Linkdin free credits? Google Adwords Grant?
- [ ] @rayjamesdev, setup Google doc to share notetaking tasks with others during meetings.

<br><br>
**Reports Needed:**
- [ ] Visitors from Drupal Sites
- [ ] returning users vs new users
- [ ] Keyword campaign reports?
- [ ] ctr
- [ ] What pages/behavior is happening from main page/entrance pages to site.

<br><br>
**What counts as a Conversion and/or what is important data/behavior to track?:**
- Call to action
- Downloading Backdrop
- Implement a Backdrop site
- spin up a demo site
- Filling out the contractor referral form (D7 pipeline)
- Use the forum

**Comment by rayjamesdev** [comment]
Meeting notes from 04/05/2023

Notes:

- @keiserjb and @stpaultim are the main dudes forming the task force. Ray also helping when he can.
- @stpaultim got @keiserjb access to both Backdropcms.org and forum.backdropcms.org Google Analytics accounts.
- @keiserjb did determine that GA4 is working for both sites.
- @keiserjb did not see Google Search Console as connected to either account and needs @jenlampton to help find this out and if set up, add @keiserjb as an administrator.

Links shared in meeting:
- https://moz.com/free-seo-tools
- https://github.com/backdrop-ops/backdrop-community/issues
- https://backdropcms.org/project/hotjar
- https://conversionsciences.com/

**Comment by jenlampton** [comment]
> backlinks from backdrop github project pages to project page on backdrop site

I wonder if we can automate this.

**Comment by rayjamesdev** [comment]
04/12/2023 Meeting Notes:
- @keiserjb began setting up a Looker Studio dashboard for backdropcms.org. Here is the first report: https://lookerstudio.google.com/u/0/reporting/80fdc732-fde9-4f8a-a89b-eb8757f9f272?s=shU70P0JWXM
- Hotjar or crazyegg or https://www.neuronsinc.com/
     - @rayjamesdev made contact with https://www.neuronsinc.com/ a week prior to see if they would sponsor backdropcms.org as an open source project.  Currently in conversation with them.
- Talked about conversion tracking
- Took a look at Google Optimize, will revisit later on, but still really neat.
- Went into Search Console and did a mini-audit of backdropcms.org. Will need to revisit as there are some potential issues, but overall looks good.  Will need a deeper dive during the official site audit.
     - During that audit, we found some Drupal keywords that we can better incorporate in order to get higher rankings.  See next comment.
- We determined that the quickest/easiest change we can make with the most impact is to fix up the metadata/title tags on the front page of backdropcms.org to include some Drupal keywords(based on audit), which will dramatically increase our rankings for those highly searched keywords.  One of the highest, most important being the keyword: Drupal Alternatives(with the s) among a few others.  This will become our first actionable todo for the task force.  See first Todo here: https://github.com/backdrop-ops/backdrop-community/issues/25#issue-1656307882

**Comment by yorkshire-pudding** [comment]
>  backlinks from backdrop github project pages to project page on backdrop site.

All mine (except bee) have backlinks to backdropcms.org.  However, the `noopener noreferrer nofollow` tags are added to the link under "About" and `nofollow` is added to any in the README.  How much SEO benefit do these links generate? I guess it's not zero, but not as good as a link without any of these tage.

```html
<a title="https://backdropcms.org/project/paragraphs_jquery_ui_accordion2" role="link" target="_blank" rel="noopener noreferrer nofollow" class="text-bold" href="https://backdropcms.org/project/paragraphs_jquery_ui_accordion2">backdropcms.org/project/paragraphs_jquery_ui_accordion2</a>
```

**Comment by jenlampton** [comment]
We added those attributes to backdrop links as part of a fix for a security issue. I bet GitHub did the same.

**Comment by yorkshire-pudding** [comment]
However, some aspects of the backdrop-contrib projects we could work on are:
-  the project description which is added to the meta title and many other meta tags - avoid using that to say "port of Drupal 7 module" (what a waste of metadata!); say what is does for Backdrop CMS (e.g. "An accordion display for any paragraph content on Backdrop CMS")
- the topics which get repos added to pages like this: https://github.com/topics/backdropcms - use `backdrop`, `backdropcms`, and any relevant functional topics (e.g. `paragraphs`, `accordion`).

![image](https://user-images.githubusercontent.com/20357797/231990802-2be48803-3f45-4660-8409-68cbd7e60ffc.png)

Readme's could be looked at as many have too many drupal mentions where the readme has not been ported.  Yes, we need some mentions, but we should link to Backdrop installation instructions and talk more about Backdrop CMS.  The more mentions of "backdropcms" or "Backdrop CMS" we get out there, even if the links aren't spidered, then we raise exposure.

**Comment by keiserjb** [comment]
I'm wondering about the github projects surfacing in Google searches.  I've been working with Views Natural Sort both in Backdrop and Drupal.

I'm searching for this, which is in the Backdrop issue queue.

```
Notice: Undefined property: File::$name in views_natural_sort_views_natural_sort_queue_rebuild_data() (line 146 of /var/www/html/backdrop1/modules/contrib/views_natural_sort/views_natural_sort.module).
Notice: Undefined property: File::$mime in views_natural_sort_views_natural_sort_queue_rebuild_data() (line 146 of /var/www/html/backdrop1/modules/contrib/views_natural_sort/views_natural_sort.module).
```

I get the Drupal issue at the top of my search results.  Backdrop is not there.

![image](https://user-images.githubusercontent.com/41843284/232050604-81ef5762-6871-42f8-af54-f2dfd683a593.png)

**Comment by yorkshire-pudding** [comment]
Some discussion here about what gets indexed and why.  https://github.com/orgs/community/discussions/4992 I can't find out why issues are not being indexed; someone on that discussion reported it after moving, but these orgs have been around for a long time.  I have found that readme and the About section is indexed so the more we mention Backdrop there, the better.

**Comment by keiserjb** [comment]
We probably have little control over what GitHub does but it could be the root of the problem when we Google errors.  Most users are not going to start by searching inside GitHub for core or contrib issues because they don't know to go there.

**Comment by yorkshire-pudding** [comment]
Perhaps we could use the API to expose outside? Do your React headless skills lend themselves to this kind of thing?

**Comment by keiserjb** [comment]
An interesting idea but that is larger than anything I have attempted.

**Comment by keiserjb** [comment]
Hmm....so we could publish our repos and issue queues with GitHub pages?

https://github.com/learntocloud/learn-to-cloud/issues/54

https://github.com/orgs/community/discussions/23571

**Comment by jenlampton** [comment]
I do have success googling error messages and getting github issues as results (sometimes). I don't think having duplicate content will help us at all -- google hates that and may penalize our site if it finds we are duplicating other content it already has indexed.

**Comment by yorkshire-pudding** [comment]
What if we didn't duplicate the content, but had a list of titles with links to the issues?

**Comment by jenlampton** [comment]
Would duplicating the titles be helpful? I find they are often "My thing is broken" and the real value is in the description and/or comment thread. (But it would be an alternative that wouldn't get penalized!)

**Comment by yorkshire-pudding** [comment]
My thoughts were that the value is we could add links to the issues without any `nofollow` tags so we could ensure that they got indexed. I think that would work as I couldn't find any tags that would stop it and the `robots.txt` doesn't exclude individual issues, just the search page.

**Comment by keiserjb** [comment]
I can understand the penalties but the end result of somehow getting the issue queues with all of the comments indexed might be worth it.

**Comment by jenlampton** [comment]
Can we check on the new feature issues in core issue queue? Because we already have links to those issues on the forum site. https://forum.backdropcms.org/feature-requests

If those are getting the attention we want, we'll know that this will help.
