### ISSUE TITLE
[Meta] Backdrop LIVE - Sept 2023

### ISSUE THREAD

**Issue by stpaultim** [backdrop-ops/backdrop-community#30]
Backdrop Live is scheduled for Sept 22 & 23. That's in 42 days.

- [x] Open registration
- [ ] https://github.com/backdrop-ops/backdrop-community/issues/31
- [ ] https://github.com/backdrop-ops/backdrop-community/issues/33
- [x] https://github.com/backdrop-ops/backdrop-community/issues/35
- [ ] Create a Facebook event
- [ ] https://github.com/backdrop-ops/backdrop-community/issues/37
- [ ] Create social media graphics
- [ ] https://github.com/backdrop-ops/backdrop-community/issues/36
- [x] Get listed on Drupal events calendar
- [ ] ...

---

It's time to start doing All The Things.

What are those things?

To open registration:

1. edit event node
2. Remove "tentative" from node title
3. Set **registration type** to `Backdrop Live`
4. Save 
5. click on **manage registrations** tab
6. select **settings** sub-tab
7. set Registration open + close **dates**
8. scroll down and set **Spaces allowed** to something like 200
9. set the **Confirmation redirect path** to `donate`.
10. Save settings

Once registration is open, you can tell the website that registration is open by visiting `admin/config/event` and changing the answer to **Is Registration open**? from "no" to "yes"

[Edited by @cellear and @jenlampton]

**Comment by cellear** [comment]
Backdrop Live is scheduled for Sept 22 & 23.  That's in 42 days.

It's time to start doing All The Things.

What are those things?

**Comment by irinaz** [comment]
- Remove tentative here https://events.backdropcms.org/events/backdrop-live-september-2023-tentative 
- I changed registration to current year and Register button does not work in right sidebar @jenlampton ?
 - Create good poster type image 
 - Begin posting information in various channels and send direct invitations to present topics and to attend sessions

This was one image where I liked content very much
 (https://fibonacciwebstudio.com/sites/default/files/field/image/backdrop-marketing.png)

**Comment by jenlampton** [comment]
> Remove tentative here [events.backdropcms.org/events/backdrop-live-september-2023-tentative](https://events.backdropcms.org/events/backdrop-live-september-2023-tentative)

done

> I changed registration to current year

I have no idea what this means, but whatever you did probably wasn't necessary?

> Register button does not work in right sidebar @jenlampton ?

@irinaz registration was not open for the event. 

To open registration:
1) edit event node
2) Set **registration type** to `Backdrop Live`
3) Save
4) click on **manage registrations** tab
5) select **settings** sub-tab
6) set open + close dates
7) scroll down and set **Spaces allowed** to something like 100
8) set the "Confirmation redirect path" to `donate`.
9) Save settings"

Once registration is open, you can tell the website that registration is open by visiting `admin/config/event` and changing the answer to **Is Registration open**? from "no" to "yes"

edit: I just copied this list into the Original Post
double edit: I also added these steps (and some other info) onto the https://events.backdropcms.org/admin/config/event page.

**Comment by cellear** [comment]
> edit: I just copied this list into the Original Post
> double edit: I also added these steps (and some other info) onto the https://events.backdropcms.org/admin/config/event page.

@jenlampton: I don't have access to that page, which suggests to me that I'm probably lacking permissions I'll need to do other stuff as well.
<img width="774" alt="Screenshot 2023-08-13 at 11 16 08 AM" src="https://github.com/backdrop-ops/backdrop-community/assets/757296/c162a114-0f12-4cab-a249-30a108a3cb19">

**Comment by jenlampton** [comment]
@cellear  That screenshot looks fine to me. What does the page look like after you log in or register?

**Comment by jenlampton** [comment]
@cellear You are currently an editor on the site, so you wouldn't have access to those settings. What is the other stuff you'll need to do? Maybe you need to be an event admin?

edit:  I just did a permissions audit and separated event-admin stuff from developer stuff so we can make more people event admins safely. (@cellear  I made you an event admin) 

There are a lot of developers on the site though. They are all trusted members of our community, so dont think we need to do anything about it immediately, but it makes me a little nervous. Maybe we should do periodical checks (on all our sites) of the number of accounts that have access to kill switches. I'll make a separate issue for that somewhere :)

**Comment by stpaultim** [comment]
It seems to me that registration is configured and working. I'll ask folks in Zulip to test it. 
https://events.backdropcms.org

**Comment by yorkshire-pudding** [comment]
> There are a lot of developers on the site though. They are all trusted members of our community, so dont think we need to do anything about it immediately, but it makes me a little nervous. Maybe we should do periodical checks (on all our sites) of the number of accounts that have access to kill switches. I'll make a separate issue for that somewhere :)

@jenlampton - I only really need event admin so have downgraded my permissions on that site.
